version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    env_file:
      - .env
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8020:8000'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
    ports:
      - '5432:5432'
