version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    environment:
      DEBUG: true
      SECRET_KEY: 3+$($${l})*g1v3*7c91^vs+!b^af89cf8)73n6-c2h-f-upgmtf@zh(
      DATABASE_URL: postgres://postgres:postgres@postgres/postgres
    tty: true
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 3s
    ports:
      - '5432:5432'
