# Generated by Django 4.2.1 on 2023-05-10 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='current_location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_confirmed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_guide',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_tourist',
        ),
    ]
