# Generated by Django 4.2.2 on 2023-07-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_guideprofile_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_card_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
