# Generated by Django 4.2.1 on 2023-06-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_guideprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideprofile',
            name='verification_status',
            field=models.CharField(choices=[('NOT VERIFIED', 'Непроверен'), ('SENT TO VERIFICATION', 'Отправлен на проверку'), ('SENT TO REWORK', 'Отправлен на доработку'), ('CONFIRMED', 'Подтвержден'), ('REFUSED', 'Отказ'), ('FINISHED', 'Завершён')], default='NOT VERIFIED', max_length=256),
        ),
    ]
