# Generated by Django 4.2.1 on 2023-05-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(max_length=2048, null=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='certificates',
            field=models.FileField(null=True, upload_to='certificates', verbose_name='Сертификаты'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_location',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience_resume',
            field=models.FileField(null=True, upload_to='experience_resumes', verbose_name='Резюме с опытом'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.CharField(max_length=512, null=True, verbose_name='Языки'),
        ),
    ]
