# Generated by Django 4.2.1 on 2023-05-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_about_alter_profile_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bank_details',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
