# Generated by Django 4.2.1 on 2023-05-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_bank_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verification_status',
            field=models.CharField(choices=[('NOT VERIFIED', 'Непроверен'), ('SENT TO VERIFICATION', 'Отправлен на проверку'), ('SENT TO REWORK', 'Отправлен на доработку'), ('CONFIRMED', 'Подтвержден'), ('REFUSED', 'Отказ')], default='NOT VERIFIED', max_length=256),
        ),
    ]
