# Generated by Django 4.2.1 on 2023-06-01 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='tourists',
            field=models.ManyToManyField(related_name='booked_tour', through='booking.Booking', to=settings.AUTH_USER_MODEL),
        ),
    ]
