# Generated by Django 4.2.2 on 2023-06-14 13:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0002_alter_tour_end_date_alter_tour_moderation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correspondence', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Соответствие тура описанию')),
                ('professionalism', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Профессионализм гида')),
                ('text_review', models.TextField(max_length=3000, verbose_name='Текстовый отзыв')),
                ('moderation_status', models.CharField(choices=[('NOT VERIFIED', 'Непроверен'), ('SENT TO VERIFICATION', 'Отправлен на проверку'), ('SENT TO REWORK', 'Отправлен на доработку'), ('CONFIRMED', 'Подтвержден'), ('REFUSED', 'Отказ'), ('FINISHED', 'Завершён'), ('STARTED', 'Начался')], default='NOT VERIFIED', max_length=256)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_rating', to='tours.tour')),
                ('tourist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_by_tourist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
