# Generated by Django 4.2.1 on 2023-05-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tour_end_date_alter_tour_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name': 'Тур', 'verbose_name_plural': 'Туры'},
        ),
    ]
