# Generated by Django 4.2.2 on 2023-06-14 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='moderation_status',
        ),
    ]
