# Generated by Django 4.2.2 on 2023-06-14 16:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tours', '0004_alter_rating_options_remove_rating_moderation_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rating',
            new_name='TourRating',
        ),
    ]
