# Generated by Django 4.2.1 on 2023-05-21 16:42

from django.db import migrations, models
import tours.models.tour


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tour_options_tour_moderation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='end_date',
            field=models.DateField(validators=[tours.models.tour.date_validation], verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='start_date',
            field=models.DateField(validators=[tours.models.tour.date_validation], verbose_name='Дата старта'),
        ),
    ]
