# Generated by Django 4.2.1 on 2023-05-21 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_tour_options'),
        ('tours', '0005_alter_tour_end_date_alter_tour_start_date'),
    ]

    operations = [
    ]
