# Generated by Django 4.2.2 on 2023-06-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_rename_rating_tourrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourrating',
            name='text_review',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Текстовый отзыв'),
        ),
    ]
