# Generated by Django 4.2.1 on 2023-05-25 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
        ('tours', '0006_merge_20230521_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='bookings',
            field=models.ManyToManyField(related_name='booked_tour', through='booking.Booking', to=settings.AUTH_USER_MODEL),
        ),
    ]
