# Generated by Django 4.2.2 on 2023-06-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tourimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
