# Generated by Django 4.2.3 on 2023-07-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_tourimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='moderation_status',
            field=models.CharField(choices=[('NOT VERIFIED', 'Непроверен'), ('SENT TO VERIFICATION', 'Отправлен на проверку'), ('SENT TO REWORK', 'Отправлен на доработку'), ('CONFIRMED', 'Подтвержден'), ('REFUSED', 'Отказ'), ('FINISHED', 'Завершён'), ('STARTED', 'Начался'), ('CANCELED', 'Отменено')], default='NOT VERIFIED', max_length=256),
        ),
    ]
