# Generated by Django 4.2.2 on 2023-06-22 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_tour_booking_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя пассажира')),
                ('last_name', models.CharField(max_length=256, verbose_name='Фамилия пассажира')),
                ('birthdate', models.DateField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='booking.booking', verbose_name='Бронирование')),
            ],
        ),
    ]
