# Generated by Django 4.2.2 on 2023-06-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('RESERVED', 'Зарезервирован'), ('HOLD', 'Удержано'), ('CANCELED', 'Отменено'), ('SENT TO VERIFICATION', 'Отправлен на проверку')], default='SENT TO VERIFICATION', max_length=256),
        ),
    ]
