# Generated by Django 4.2.2 on 2023-06-28 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('RESERVED', 'Зарезервирован'), ('HOLD', 'Удержано'), ('CANCELED', 'Отменено'), ('SENT TO VERIFICATION', 'Отправлен на проверку')], default='SENT TO VERIFICATION', max_length=256),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='booking.booking', verbose_name='Бронирование'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Имя пассажира'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(max_length=256, null=True, verbose_name='Фамилия пассажира'),
        ),
    ]
