# Generated by Django 4.2.2 on 2023-06-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя пассажира'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия пассажира'),
        ),
    ]
