# Generated by Django 4.2.3 on 2023-07-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='Имя пассажира'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(max_length=256, verbose_name='Фамилия пассажира'),
        ),
    ]
