# Generated by Django 4.2.3 on 2023-07-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_passenger_birthdate_alter_passenger_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('CREATED', 'Создан'), ('RESERVED', 'Зарезервирован'), ('HOLD', 'Удержано'), ('CANCELED', 'Отменено'), ('PAYED', 'Оплачено')], default='CREATED', max_length=256),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transaction_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID транзакции CP'),
        ),
    ]
