# Generated by Django 4.2.3 on 2023-07-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_booking_booking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reserved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
