on:
  pull_request:
    branches:
      - dev

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install -r requirements/dev.txt
      - run: flake8 .

  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        environment:
          POSTGRES_PASSWORD: postgres
        healthcheck:
          test: pg_isready -U postgres
          interval: 3s
        ports:
          - '5432:5432'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt

        env:
          DEBUG: "1"
          SECRET_KEY: "3+($${l})*g1v3*7c91^vs+!b^af89cf8)73n6-c2h-f-upgmtf@zh("
          DATABASE_URL: "postgres://postgres:postgres@postgres/postgres"
          PAYMENT_LOGIN: "pk_aad02fa59dec0bacabf00955821fd"
          PAYMENT_PASS: "9b431e1c5d36c6c36d01b7635751af5f"
          PAYMENT_URL: "https://api.cloudpayments.ru/payments"
